require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'
# Standard Notes Specific
pod 'TrustKit', '1.6.5'

# Enables Flipper.
#
# Note that if you have use_frameworks! enabled, Flipper will not work and
# you should disable these next few lines.
# post_install do |installer|
#   flipper_post_install(installer)
# end

target 'StandardNotes' do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end

target "StandardNotesDev" do
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
end
